/*
 * This source file was generated by the Gradle 'init' task
 */
package io.temporal.samples.hello

import io.temporal.testing.TestEnvironmentOptions
import io.temporal.testing.TestWorkflowEnvironment
import io.temporal.worker.WorkerFactory
import io.temporal.worker.WorkerOptions
import io.temporal.worker.tuning.PollerBehaviorAutoscaling
//import io.temporal.worker.tuning.PollerBehaviorAutoscaling
import java.time.Duration
import kotlin.test.BeforeTest
import kotlin.test.Test
import java.time.Instant.now
import kotlin.test.assertEquals


class StarterTest {
    private lateinit var testEnv: TestWorkflowEnvironment

    @BeforeTest
    fun setup() {
        val opts = TestEnvironmentOptions.newBuilder()
//            .setUseExternalService(true)
            .build()
        testEnv = TestWorkflowEnvironment.newInstance(opts)
        val workerFactory = WorkerFactory.newInstance(testEnv.workflowClient)
        workerFactory.newWorker("HelloActivityTaskQueue", WorkerOptions.newBuilder().apply {
            setWorkflowTaskPollersBehavior(
                PollerBehaviorAutoscaling(2, 5, 2)
            )
        }.build()).apply {
            registerWorkflowImplementationTypes(GreetingWorkflowImpl::class.java)
            registerActivitiesImplementations(GreetingActivitiesImpl())

        }
        workerFactory.start()
    }

    @Test
    fun greeting() {
        println("Starting Test at ${now()}")

        val starter1 = Starter(testEnv.workflowClient, startDelay = Duration.ofSeconds(2))
        val handle = starter1.spawn("Gaurav")

        println("status 1: ${starter1.status(handle)}")
        val result = starter1.getResult(handle)
        println("result: $result")

        assertEquals(result, "hello, Gaurav!")
    }
}
