/* * This source file was generated by the Gradle 'init' task */
package io.temporal.samples.Schedule

import io.temporal.api.taskqueue.v1.TaskQueue
import io.temporal.api.workflowservice.v1.DescribeTaskQueueRequest
import io.temporal.api.workflowservice.v1.ListSchedulesRequest
import io.temporal.client.WorkflowOptions
import io.temporal.client.schedules.Schedule
import io.temporal.client.schedules.ScheduleAction
import io.temporal.client.schedules.ScheduleActionStartWorkflow
import io.temporal.client.schedules.ScheduleCalendarSpec
import io.temporal.client.schedules.ScheduleClient
import io.temporal.client.schedules.ScheduleOptions
import io.temporal.client.schedules.ScheduleRange
import io.temporal.client.schedules.ScheduleSpec
import io.temporal.worker.WorkerOptions
import kotlin.streams.toList

const val TASK_QUEUE = "HelloActivityTaskQueue"

fun worker() {
    val workflowClient = localClient(
        withMetrics = false,
        namespace = "gaurav-test.a2dd6",
    )


    ScheduleClient.newInstance(workflowClient.workflowServiceStubs).createSchedule(
        "MySampleSchedule",
        Schedule.newBuilder()
            .setAction(ScheduleActionStartWorkflow.newBuilder()
                .setWorkflowType("SomeWF")
                .setArguments("some args")
                .setOptions(WorkflowOptions.newBuilder().setWorkflowId("WF-id").setTaskQueue("my-queue").build())
                .build())
            .setSpec(spec())
            .build(),
        ScheduleOptions.newBuilder().build(),
    )

}

private fun spec(): ScheduleSpec? = ScheduleSpec.newBuilder().setCalendars(specs()).build()

private fun specs(): List<ScheduleCalendarSpec> = listOf<ScheduleCalendarSpec>(
    ScheduleCalendarSpec.newBuilder()
//        .setHour(
//            listOf(ScheduleRange(0, 23, 1))
//        )
        .setMinutes(
            listOf(ScheduleRange(8, 53, 15))
        )
        .build()
)


