/*
 * This source file was generated by the Gradle 'init' task
 */
package io.temporal.samples.QueueDepthSample

import io.temporal.api.common.v1.WorkflowExecution
import io.temporal.api.enums.v1.WorkflowExecutionStatus
import io.temporal.client.WorkflowClient
import io.temporal.client.WorkflowOptions
import java.time.Duration
import java.util.*


const val TASK_QUEUE = "HelloActivityTaskQueue"

class Starter(
    private val client: WorkflowClient,
    private val startDelay: Duration
) {
    private fun workflowStub() = WorkflowOptions.newBuilder().apply {
        setWorkflowId("WORKFLOW_ID_${UUID.randomUUID()}")
        setTaskQueue(TASK_QUEUE)
//        setStartDelay(startDelay)
    }.build().let { wo ->
        client.newWorkflowStub(
            GreetingWorkflow::class.java, wo
        )
    }

    fun spawn(arg: String): WorkflowExecution {
        val we = WorkflowClient.start(workflowStub()::greeting, arg)
        val time = client.newUntypedWorkflowStub(we.workflowId).describe().executionTime
        println("Initiate workflow at ${time}")
        return we
    }

    fun status(handle: WorkflowExecution): WorkflowExecutionStatus {

        return client.newUntypedWorkflowStub(handle.workflowId).describe().status
    }

    fun getResult(handle: WorkflowExecution): String {
        return client.newUntypedWorkflowStub(handle.workflowId).getResult(String::class.java)
    }


}

fun starter() {
    val starter = Starter(client(namespace = "gaurav-test.a2dd6"), startDelay = Duration.ofSeconds(0))
    val arg = "Thadani  ${UUID.randomUUID()}"
    starter.spawn(arg)


    println("Created ${arg}")
}




