/* * This source file was generated by the Gradle 'init' task */
package io.temporal.samples.QueueDepthSample

import io.temporal.api.enums.v1.DescribeTaskQueueMode
import io.temporal.api.enums.v1.TaskQueueType
import io.temporal.api.taskqueue.v1.TaskQueue
import io.temporal.api.workflowservice.v1.DescribeTaskQueueRequest
import io.temporal.worker.WorkerFactory
import io.temporal.worker.WorkerOptions
//import io.temporal.worker.tuning.PollerBehaviorAutoscaling
import java.time.Duration
import kotlin.system.exitProcess


fun worker() {
    val workflowClient = client(
        withMetrics = false,
        namespace = "gaurav-test.a2dd6"
    )
    val describeTaskQueueResponse = workflowClient.workflowServiceStubs.blockingStub().describeTaskQueue(
        DescribeTaskQueueRequest.newBuilder()
            .setTaskQueue(TaskQueue.newBuilder().setName(TASK_QUEUE).build())
            .setReportStats(true)
            .setNamespace("gaurav-test.a2dd6")
            .build()
    )

    println(describeTaskQueueResponse)

//    WorkerFactory.newInstance(
//        workflowClient
//    ).also { factory ->
//        factory.newWorker(TASK_QUEUE, WorkerOptions.newBuilder().apply {
//            setDefaultHeartbeatThrottleInterval(Duration.ofSeconds(10))
//
//
//        }.build()).apply {
//            registerWorkflowImplementationTypes(GreetingWorkflowImpl::class.java)
//            registerActivitiesImplementations(GreetingActivitiesImpl())
//        }
//    }.start()
}


