/* * This source file was generated by the Gradle 'init' task */
package io.temporal.samples.cube_nde

import io.temporal.samples.Schedule.localClient
import io.temporal.worker.WorkerFactory
import io.temporal.worker.WorkerOptions
import io.temporal.worker.WorkflowImplementationOptions


fun worker() {
    val workflowClient = localClient(
        withMetrics = false,
    )

    WorkerFactory.newInstance(
        workflowClient
    ).also { factory ->
        factory.newWorker(TASK_QUEUE, WorkerOptions.newBuilder().build()).apply {

            val options = WorkflowImplementationOptions.newBuilder()
                .setEnableUpsertVersionSearchAttributes(true)
                .build()
            registerWorkflowImplementationTypes(options, GreetingWorkflowImpl::class.java)
            registerActivitiesImplementations(ActivityImpl())
        }
    }.start()
}
