/* * This source file was generated by the Gradle 'init' task */
package io.temporal.samples.hello

import io.temporal.api.enums.v1.DescribeTaskQueueMode
import io.temporal.api.enums.v1.TaskQueueType
import io.temporal.api.taskqueue.v1.TaskQueue
import io.temporal.api.workflowservice.v1.DescribeTaskQueueRequest
import io.temporal.samples.Schedule.localClient
import io.temporal.worker.WorkerFactory
import io.temporal.worker.WorkerOptions
//import io.temporal.worker.tuning.PollerBehaviorAutoscaling
import java.time.Duration
import kotlin.system.exitProcess


fun worker() {
    val workflowClient = localClient(
        withMetrics = false,
        namespace = "gaurav-mrn.a2dd6"
    )

    WorkerFactory.newInstance(
        workflowClient
    ).also { factory ->
        factory.newWorker(TASK_QUEUE, WorkerOptions.newBuilder().apply {
            setDefaultHeartbeatThrottleInterval(Duration.ofSeconds(10))
//            setMaxTaskQueueActivitiesPerSecond(1)


        }.build()).apply {
            registerWorkflowImplementationTypes(GreetingWorkflowImpl::class.java)
            registerWorkflowImplementationTypes(SignallerWorkflowImpl::class.java)
            registerActivitiesImplementations(GreetingActivitiesImpl())
            registerActivitiesImplementations(SignalActivitiesImpl())
            factory.suspendPolling()
        }
    }.start()
}


