/* * This source file was generated by the Gradle 'init' task */
package io.temporal.samples.hello

import io.temporal.worker.WorkerFactory
import io.temporal.worker.WorkerOptions
//import io.temporal.worker.tuning.PollerBehaviorAutoscaling
import java.time.Duration


fun worker() {
    WorkerFactory.newInstance(
        localClient(
            withMetrics = false,
            namespace = "gaurav-test.a2dd6"
        )
    ).also { factory ->
        factory.newWorker(TASK_QUEUE, WorkerOptions.newBuilder().apply {
            setDefaultHeartbeatThrottleInterval(Duration.ofSeconds(10))
//            setWorkflowTaskPollersBehavior(
//                PollerBehaviorAutoscaling(2, 5, 2)
//            )
        }.build()).apply {
            registerWorkflowImplementationTypes(GreetingWorkflowImpl::class.java)
            registerActivitiesImplementations(GreetingActivitiesImpl())
        }
    }.start()
}


