/*
 * This source file was generated by the Gradle 'init' task
 */
package io.temporal.samples.update_nde

import io.temporal.api.common.v1.WorkflowExecution
import io.temporal.api.enums.v1.WorkflowExecutionStatus
import io.temporal.client.WorkflowClient
import io.temporal.client.WorkflowOptions
import io.temporal.client.WorkflowStub
import io.temporal.samples.QueueDepthSample.localClient
import java.time.OffsetDateTime
import java.util.*


const val TASK_QUEUE = "HelloActivityTaskQueue"

class Starter(
    private val client: WorkflowClient
) {
    private fun workflowStub() = WorkflowOptions.newBuilder().apply {
        setWorkflowId("WORKFLOW_ID_${UUID.randomUUID()}")
        setTaskQueue(TASK_QUEUE)
    }.build().let { wo ->
        client.newWorkflowStub(
            GreetingWorkflow::class.java, wo
        )
    }

    fun spawn(): WorkflowExecution {
        val date = OffsetDateTime.now()
        println("request: $date")
        val we = WorkflowStub.fromTyped(workflowStub()).start(date)
        return we
    }

    fun status(handle: WorkflowExecution): WorkflowExecutionStatus {
        return client.newUntypedWorkflowStub(handle.workflowId).describe().status
    }

    fun getResult(handle: WorkflowExecution): String {
        return client.newUntypedWorkflowStub(handle.workflowId).getResult(String::class.java)
    }
}

fun starter(): String =
    Starter(localClient(namespace = "gaurav-mrn.a2dd6")).spawn().workflowId



