/* * This source file was generated by the Gradle 'init' task */
package io.temporal.samples.update_nde

import io.temporal.samples.Schedule.localClient
import io.temporal.worker.WorkerFactory
import io.temporal.worker.WorkerOptions
import java.time.Duration


fun worker() {
    val workflowClient = localClient(
        withMetrics = false,
        namespace = "gaurav-mrn.a2dd6"
    )

    WorkerFactory.newInstance(
        workflowClient
    ).also { factory ->
        factory.newWorker(TASK_QUEUE, WorkerOptions.newBuilder().build()).apply {
            registerWorkflowImplementationTypes(GreetingWorkflowImpl::class.java)
            registerActivitiesImplementations(GreetingActivitiesLocalImpl())

            factory.suspendPolling()
        }
    }.start()
}



fun activityWorker() {
    val workflowClient = localClient(
        withMetrics = false,
        namespace = "gaurav-mrn.a2dd6"
    )

    WorkerFactory.newInstance(
        workflowClient
    ).also { factory ->
        factory.newWorker(TASK_QUEUE, WorkerOptions.newBuilder().build()).apply {
            registerActivitiesImplementations(GreetingActivitiesImpl())
            factory.suspendPolling()
        }
    }.start()
}


